#ifndef ATA_H
#define ATA_H

#define ATA_PRI_BASE        0x1F0
#define ATA_PRI_DATA_PORT   (ATA_PRI_BASE+0)
#define ATA_PRI_ERRO_PORT   (ATA_PRI_BASE+1)
#define ATA_PRI_SECT_PORT   (ATA_PRI_BASE+2)
#define ATA_PRI_LBAlo_PORT  (ATA_PRI_BASE+3)
#define ATA_PRI_LBAmid_PORT (ATA_PRI_BASE+4)
#define ATA_PRI_LBAhi_PORT  (ATA_PRI_BASE+5)
#define ATA_PRI_DRIVE_PORT  (ATA_PRI_BASE+6)
#define ATA_PRI_STATUS_PORT (ATA_PRI_BASE+7)
#define ATA_PRI_CMD_PORT    (ATA_PRI_BASE+7)

#define ATA_SEC_BASE 0x170
#define ATA_SEC_DATA_PORT   (ATA_SEC_BASE+0)
#define ATA_SEC_ERRO_PORT   (ATA_SEC_BASE+1)
#define ATA_SEC_SECT_PORT   (ATA_SEC_BASE+2)
#define ATA_SEC_LBAlo_PORT  (ATA_SEC_BASE+3)
#define ATA_SEC_LBAmid_PORT (ATA_SEC_BASE+4)
#define ATA_SEC_LBAhi_PORT  (ATA_SEC_BASE+5)
#define ATA_SEC_DRIVE_PORT  (ATA_SEC_BASE+6)
#define ATA_SEC_STATUS_PORT (ATA_SEC_BASE+7)
#define ATA_SEC_CMD_PORT    (ATA_SEC_BASE+7)

void identify(void);
#endif